version: '3.4'

services:

    db:
        build:
            context: ./config/postgres
            network: host
        container_name: db
        env_file:
            - config/postgres/postgres.env
        volumes:
            - ./config/postgres/data:/var/lib/postgres/data
        networks:
            codepdxnet:
                ipv4_address: 172.16.238.2
      

    # expungeservice:
      

    # webserver:
    

networks:
    codepdxnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
        driver_opts:
            com.docker.network.bridge.name: codepdxnet
