version: '3.4'

services:

    db:
        build:
            context: ./config/postgres
            network: host
        container_name: db
        env_file:
            - config/postgres/postgres.env
        volumes:
            - ./config/postgres/data:/var/lib/postgres/data
        networks:
            codepdxnet:
                ipv4_address: 172.16.238.2

    expungeservice:
        build:
            context: ./src/backend/expungeservice
            network: host
        container_name: expungeservice
        env_file:
            - config/expungeservice/expungeservice.env
        volumes:
            - ./src/backend/expungeservice:/var/www/expungeservice
        ports:
            - "5000:5000"
        networks:
            codepdxnet:
                ipv4_address: 172.16.238.3


    # webserver:
    

networks:
    codepdxnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
        driver_opts:
            com.docker.network.bridge.name: codepdxnet
